/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#f0eded',
        'on-background': '#1c1b1b',
        'secondary-fixed': '#a6efef',
        surface: '#fcf9f8',
        'on-primary-fixed': '#002020',
        'surface-container-high': '#eae7e7',
        'on-secondary': '#ffffff',
        'secondary-container': '#a3edec',
        'surface-container-low': '#f6f3f2',
        'primary-fixed-dim': '#76d6d5',
        'surface-tint': '#006a6a',
        'on-error-container': '#93000a',
        'on-surface': '#1c1b1b',
        'inverse-surface': '#313030',
        'on-secondary-fixed-variant': '#004f4f',
        primary: '#006565',
        'secondary-fixed-dim': '#8ad3d2',
        'on-primary': '#ffffff',
        'inverse-primary': '#76d6d5',
        'on-primary-container': '#e3fffe',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        tertiary: '#515c5d',
        'tertiary-container': '#697575',
        'on-secondary-fixed': '#002020',
        'primary-container': '#008080',
        error: '#ba1a1a',
        'on-secondary-container': '#1d6d6d',
        'error-container': '#ffdad6',
        secondary: '#166969',
        'tertiary-fixed-dim': '#bdc9c9',
        'on-error': '#ffffff',
        'tertiary-fixed': '#d9e5e5',
        'on-tertiary-fixed': '#131d1e',
        'surface-bright': '#fcf9f8',
        'surface-variant': '#e5e2e1',
        'surface-container-highest': '#e5e2e1',
        'primary-fixed': '#93f2f2',
        'outline-variant': '#bdc9c8',
        'surface-dim': '#dcd9d9',
        'on-tertiary-container': '#f0fcfc',
        'on-primary-fixed-variant': '#004f4f',
        outline: '#6e7979',
        'on-surface-variant': '#3e4949',
        'on-tertiary-fixed-variant': '#3e4949',
        background: '#fcf9f8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '48px',
        md: '24px',
        xl: '80px',
        xs: '4px',
        'container-max': '1200px',
        base: '8px',
        gutter: '24px',
        sm: '12px',
      },
      fontFamily: {
        'label-sm': ['Fustat', 'sans-serif'],
        h2: ['Fustat', 'sans-serif'],
        'body-lg': ['Fustat', 'sans-serif'],
        h3: ['Fustat', 'sans-serif'],
        h1: ['Fustat', 'sans-serif'],
        'body-md': ['Fustat', 'sans-serif'],
        'label-md': ['Fustat', 'sans-serif'],
        fustat: ['Fustat', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
        h2: ['32px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
